# 线上配置文件
server:
  port: 8102
  servlet:
    session:
      cookie:
        max-age: 2592000
        same-site: none
        secure: true
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx.com/finplat
    username: root
    password: root
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
# 获取银行信息
bank:
  info:
    url: "https://ccdcapi.alipay.com/validateAndCacheCardInfo.json?_input_charset=utf-8&cardNo="
  file:
    url: "bank.json"
  logo:
    url: "https://apimg.alipay.com/combo.png?d=cashier&t="
