/*
 * 接口文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BankInfo;
import io.swagger.client.model.PageBudgetVO;
import io.swagger.client.model.PageFinancialRecordVO;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * AccountDetailsVO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-10T02:09:28.592Z")
public class AccountDetailsVO {
  @SerializedName("accountName")
  private String accountName = null;

  @SerializedName("accountNumber")
  private String accountNumber = null;

  @SerializedName("accountType")
  private Integer accountType = null;

  @SerializedName("balance")
  private BigDecimal balance = null;

  @SerializedName("bankInfo")
  private BankInfo bankInfo = null;

  @SerializedName("bankName")
  private String bankName = null;

  @SerializedName("budgetVOPage")
  private PageBudgetVO budgetVOPage = null;

  @SerializedName("createTime")
  private OffsetDateTime createTime = null;

  @SerializedName("financialRecordVOPage")
  private PageFinancialRecordVO financialRecordVOPage = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("reviewMessage")
  private String reviewMessage = null;

  @SerializedName("reviewStatus")
  private Integer reviewStatus = null;

  @SerializedName("reviewTime")
  private OffsetDateTime reviewTime = null;

  @SerializedName("updateTime")
  private OffsetDateTime updateTime = null;

  @SerializedName("userId")
  private Long userId = null;

  public AccountDetailsVO accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @ApiModelProperty(value = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public AccountDetailsVO accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @ApiModelProperty(value = "")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public AccountDetailsVO accountType(Integer accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @ApiModelProperty(value = "")
  public Integer getAccountType() {
    return accountType;
  }

  public void setAccountType(Integer accountType) {
    this.accountType = accountType;
  }

  public AccountDetailsVO balance(BigDecimal balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getBalance() {
    return balance;
  }

  public void setBalance(BigDecimal balance) {
    this.balance = balance;
  }

  public AccountDetailsVO bankInfo(BankInfo bankInfo) {
    this.bankInfo = bankInfo;
    return this;
  }

   /**
   * Get bankInfo
   * @return bankInfo
  **/
  @ApiModelProperty(value = "")
  public BankInfo getBankInfo() {
    return bankInfo;
  }

  public void setBankInfo(BankInfo bankInfo) {
    this.bankInfo = bankInfo;
  }

  public AccountDetailsVO bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Get bankName
   * @return bankName
  **/
  @ApiModelProperty(value = "")
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public AccountDetailsVO budgetVOPage(PageBudgetVO budgetVOPage) {
    this.budgetVOPage = budgetVOPage;
    return this;
  }

   /**
   * Get budgetVOPage
   * @return budgetVOPage
  **/
  @ApiModelProperty(value = "")
  public PageBudgetVO getBudgetVOPage() {
    return budgetVOPage;
  }

  public void setBudgetVOPage(PageBudgetVO budgetVOPage) {
    this.budgetVOPage = budgetVOPage;
  }

  public AccountDetailsVO createTime(OffsetDateTime createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreateTime() {
    return createTime;
  }

  public void setCreateTime(OffsetDateTime createTime) {
    this.createTime = createTime;
  }

  public AccountDetailsVO financialRecordVOPage(PageFinancialRecordVO financialRecordVOPage) {
    this.financialRecordVOPage = financialRecordVOPage;
    return this;
  }

   /**
   * Get financialRecordVOPage
   * @return financialRecordVOPage
  **/
  @ApiModelProperty(value = "")
  public PageFinancialRecordVO getFinancialRecordVOPage() {
    return financialRecordVOPage;
  }

  public void setFinancialRecordVOPage(PageFinancialRecordVO financialRecordVOPage) {
    this.financialRecordVOPage = financialRecordVOPage;
  }

  public AccountDetailsVO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AccountDetailsVO reviewMessage(String reviewMessage) {
    this.reviewMessage = reviewMessage;
    return this;
  }

   /**
   * Get reviewMessage
   * @return reviewMessage
  **/
  @ApiModelProperty(value = "")
  public String getReviewMessage() {
    return reviewMessage;
  }

  public void setReviewMessage(String reviewMessage) {
    this.reviewMessage = reviewMessage;
  }

  public AccountDetailsVO reviewStatus(Integer reviewStatus) {
    this.reviewStatus = reviewStatus;
    return this;
  }

   /**
   * Get reviewStatus
   * @return reviewStatus
  **/
  @ApiModelProperty(value = "")
  public Integer getReviewStatus() {
    return reviewStatus;
  }

  public void setReviewStatus(Integer reviewStatus) {
    this.reviewStatus = reviewStatus;
  }

  public AccountDetailsVO reviewTime(OffsetDateTime reviewTime) {
    this.reviewTime = reviewTime;
    return this;
  }

   /**
   * Get reviewTime
   * @return reviewTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getReviewTime() {
    return reviewTime;
  }

  public void setReviewTime(OffsetDateTime reviewTime) {
    this.reviewTime = reviewTime;
  }

  public AccountDetailsVO updateTime(OffsetDateTime updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(OffsetDateTime updateTime) {
    this.updateTime = updateTime;
  }

  public AccountDetailsVO userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountDetailsVO accountDetailsVO = (AccountDetailsVO) o;
    return Objects.equals(this.accountName, accountDetailsVO.accountName) &&
        Objects.equals(this.accountNumber, accountDetailsVO.accountNumber) &&
        Objects.equals(this.accountType, accountDetailsVO.accountType) &&
        Objects.equals(this.balance, accountDetailsVO.balance) &&
        Objects.equals(this.bankInfo, accountDetailsVO.bankInfo) &&
        Objects.equals(this.bankName, accountDetailsVO.bankName) &&
        Objects.equals(this.budgetVOPage, accountDetailsVO.budgetVOPage) &&
        Objects.equals(this.createTime, accountDetailsVO.createTime) &&
        Objects.equals(this.financialRecordVOPage, accountDetailsVO.financialRecordVOPage) &&
        Objects.equals(this.id, accountDetailsVO.id) &&
        Objects.equals(this.reviewMessage, accountDetailsVO.reviewMessage) &&
        Objects.equals(this.reviewStatus, accountDetailsVO.reviewStatus) &&
        Objects.equals(this.reviewTime, accountDetailsVO.reviewTime) &&
        Objects.equals(this.updateTime, accountDetailsVO.updateTime) &&
        Objects.equals(this.userId, accountDetailsVO.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountName, accountNumber, accountType, balance, bankInfo, bankName, budgetVOPage, createTime, financialRecordVOPage, id, reviewMessage, reviewStatus, reviewTime, updateTime, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountDetailsVO {\n");
    
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    bankInfo: ").append(toIndentedString(bankInfo)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    budgetVOPage: ").append(toIndentedString(budgetVOPage)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    financialRecordVOPage: ").append(toIndentedString(financialRecordVOPage)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    reviewMessage: ").append(toIndentedString(reviewMessage)).append("\n");
    sb.append("    reviewStatus: ").append(toIndentedString(reviewStatus)).append("\n");
    sb.append("    reviewTime: ").append(toIndentedString(reviewTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

