/*
 * 接口文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * AccountQueryRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-10T02:09:28.592Z")
public class AccountQueryRequest {
  @SerializedName("accountName")
  private String accountName = null;

  @SerializedName("accountNumber")
  private String accountNumber = null;

  @SerializedName("accountType")
  private Integer accountType = null;

  @SerializedName("balance")
  private BigDecimal balance = null;

  @SerializedName("bankName")
  private String bankName = null;

  @SerializedName("current")
  private Integer current = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("notId")
  private Long notId = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("reviewMessage")
  private String reviewMessage = null;

  @SerializedName("reviewStatus")
  private Integer reviewStatus = null;

  @SerializedName("reviewTime")
  private OffsetDateTime reviewTime = null;

  @SerializedName("reviewerId")
  private Long reviewerId = null;

  @SerializedName("searchText")
  private String searchText = null;

  @SerializedName("sortField")
  private String sortField = null;

  @SerializedName("sortOrder")
  private String sortOrder = null;

  @SerializedName("userId")
  private Long userId = null;

  public AccountQueryRequest accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @ApiModelProperty(value = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public AccountQueryRequest accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @ApiModelProperty(value = "")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public AccountQueryRequest accountType(Integer accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @ApiModelProperty(value = "")
  public Integer getAccountType() {
    return accountType;
  }

  public void setAccountType(Integer accountType) {
    this.accountType = accountType;
  }

  public AccountQueryRequest balance(BigDecimal balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getBalance() {
    return balance;
  }

  public void setBalance(BigDecimal balance) {
    this.balance = balance;
  }

  public AccountQueryRequest bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Get bankName
   * @return bankName
  **/
  @ApiModelProperty(value = "")
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public AccountQueryRequest current(Integer current) {
    this.current = current;
    return this;
  }

   /**
   * Get current
   * @return current
  **/
  @ApiModelProperty(value = "")
  public Integer getCurrent() {
    return current;
  }

  public void setCurrent(Integer current) {
    this.current = current;
  }

  public AccountQueryRequest id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AccountQueryRequest notId(Long notId) {
    this.notId = notId;
    return this;
  }

   /**
   * Get notId
   * @return notId
  **/
  @ApiModelProperty(value = "")
  public Long getNotId() {
    return notId;
  }

  public void setNotId(Long notId) {
    this.notId = notId;
  }

  public AccountQueryRequest pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @ApiModelProperty(value = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public AccountQueryRequest reviewMessage(String reviewMessage) {
    this.reviewMessage = reviewMessage;
    return this;
  }

   /**
   * Get reviewMessage
   * @return reviewMessage
  **/
  @ApiModelProperty(value = "")
  public String getReviewMessage() {
    return reviewMessage;
  }

  public void setReviewMessage(String reviewMessage) {
    this.reviewMessage = reviewMessage;
  }

  public AccountQueryRequest reviewStatus(Integer reviewStatus) {
    this.reviewStatus = reviewStatus;
    return this;
  }

   /**
   * Get reviewStatus
   * @return reviewStatus
  **/
  @ApiModelProperty(value = "")
  public Integer getReviewStatus() {
    return reviewStatus;
  }

  public void setReviewStatus(Integer reviewStatus) {
    this.reviewStatus = reviewStatus;
  }

  public AccountQueryRequest reviewTime(OffsetDateTime reviewTime) {
    this.reviewTime = reviewTime;
    return this;
  }

   /**
   * Get reviewTime
   * @return reviewTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getReviewTime() {
    return reviewTime;
  }

  public void setReviewTime(OffsetDateTime reviewTime) {
    this.reviewTime = reviewTime;
  }

  public AccountQueryRequest reviewerId(Long reviewerId) {
    this.reviewerId = reviewerId;
    return this;
  }

   /**
   * Get reviewerId
   * @return reviewerId
  **/
  @ApiModelProperty(value = "")
  public Long getReviewerId() {
    return reviewerId;
  }

  public void setReviewerId(Long reviewerId) {
    this.reviewerId = reviewerId;
  }

  public AccountQueryRequest searchText(String searchText) {
    this.searchText = searchText;
    return this;
  }

   /**
   * Get searchText
   * @return searchText
  **/
  @ApiModelProperty(value = "")
  public String getSearchText() {
    return searchText;
  }

  public void setSearchText(String searchText) {
    this.searchText = searchText;
  }

  public AccountQueryRequest sortField(String sortField) {
    this.sortField = sortField;
    return this;
  }

   /**
   * Get sortField
   * @return sortField
  **/
  @ApiModelProperty(value = "")
  public String getSortField() {
    return sortField;
  }

  public void setSortField(String sortField) {
    this.sortField = sortField;
  }

  public AccountQueryRequest sortOrder(String sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * Get sortOrder
   * @return sortOrder
  **/
  @ApiModelProperty(value = "")
  public String getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(String sortOrder) {
    this.sortOrder = sortOrder;
  }

  public AccountQueryRequest userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountQueryRequest accountQueryRequest = (AccountQueryRequest) o;
    return Objects.equals(this.accountName, accountQueryRequest.accountName) &&
        Objects.equals(this.accountNumber, accountQueryRequest.accountNumber) &&
        Objects.equals(this.accountType, accountQueryRequest.accountType) &&
        Objects.equals(this.balance, accountQueryRequest.balance) &&
        Objects.equals(this.bankName, accountQueryRequest.bankName) &&
        Objects.equals(this.current, accountQueryRequest.current) &&
        Objects.equals(this.id, accountQueryRequest.id) &&
        Objects.equals(this.notId, accountQueryRequest.notId) &&
        Objects.equals(this.pageSize, accountQueryRequest.pageSize) &&
        Objects.equals(this.reviewMessage, accountQueryRequest.reviewMessage) &&
        Objects.equals(this.reviewStatus, accountQueryRequest.reviewStatus) &&
        Objects.equals(this.reviewTime, accountQueryRequest.reviewTime) &&
        Objects.equals(this.reviewerId, accountQueryRequest.reviewerId) &&
        Objects.equals(this.searchText, accountQueryRequest.searchText) &&
        Objects.equals(this.sortField, accountQueryRequest.sortField) &&
        Objects.equals(this.sortOrder, accountQueryRequest.sortOrder) &&
        Objects.equals(this.userId, accountQueryRequest.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountName, accountNumber, accountType, balance, bankName, current, id, notId, pageSize, reviewMessage, reviewStatus, reviewTime, reviewerId, searchText, sortField, sortOrder, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountQueryRequest {\n");
    
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    current: ").append(toIndentedString(current)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    notId: ").append(toIndentedString(notId)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    reviewMessage: ").append(toIndentedString(reviewMessage)).append("\n");
    sb.append("    reviewStatus: ").append(toIndentedString(reviewStatus)).append("\n");
    sb.append("    reviewTime: ").append(toIndentedString(reviewTime)).append("\n");
    sb.append("    reviewerId: ").append(toIndentedString(reviewerId)).append("\n");
    sb.append("    searchText: ").append(toIndentedString(searchText)).append("\n");
    sb.append("    sortField: ").append(toIndentedString(sortField)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

