/*
 * 接口文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * BudgetEditRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-10T02:09:28.592Z")
public class BudgetEditRequest {
  @SerializedName("accountId")
  private Long accountId = null;

  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("budgetDesc")
  private String budgetDesc = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("endDate")
  private String endDate = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("startDate")
  private String startDate = null;

  public BudgetEditRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public BudgetEditRequest amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public BudgetEditRequest budgetDesc(String budgetDesc) {
    this.budgetDesc = budgetDesc;
    return this;
  }

   /**
   * Get budgetDesc
   * @return budgetDesc
  **/
  @ApiModelProperty(value = "")
  public String getBudgetDesc() {
    return budgetDesc;
  }

  public void setBudgetDesc(String budgetDesc) {
    this.budgetDesc = budgetDesc;
  }

  public BudgetEditRequest category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public BudgetEditRequest endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(value = "")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public BudgetEditRequest id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public BudgetEditRequest startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BudgetEditRequest budgetEditRequest = (BudgetEditRequest) o;
    return Objects.equals(this.accountId, budgetEditRequest.accountId) &&
        Objects.equals(this.amount, budgetEditRequest.amount) &&
        Objects.equals(this.budgetDesc, budgetEditRequest.budgetDesc) &&
        Objects.equals(this.category, budgetEditRequest.category) &&
        Objects.equals(this.endDate, budgetEditRequest.endDate) &&
        Objects.equals(this.id, budgetEditRequest.id) &&
        Objects.equals(this.startDate, budgetEditRequest.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, amount, budgetDesc, category, endDate, id, startDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BudgetEditRequest {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    budgetDesc: ").append(toIndentedString(budgetDesc)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

