/*
 * 接口文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * BudgetQueryRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-10T02:09:28.592Z")
public class BudgetQueryRequest {
  @SerializedName("accountId")
  private Long accountId = null;

  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("budgetDesc")
  private String budgetDesc = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("current")
  private Integer current = null;

  @SerializedName("endDate")
  private OffsetDateTime endDate = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("notId")
  private Long notId = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("searchText")
  private String searchText = null;

  @SerializedName("sortField")
  private String sortField = null;

  @SerializedName("sortOrder")
  private String sortOrder = null;

  @SerializedName("startDate")
  private OffsetDateTime startDate = null;

  @SerializedName("userId")
  private Long userId = null;

  public BudgetQueryRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public BudgetQueryRequest amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public BudgetQueryRequest budgetDesc(String budgetDesc) {
    this.budgetDesc = budgetDesc;
    return this;
  }

   /**
   * Get budgetDesc
   * @return budgetDesc
  **/
  @ApiModelProperty(value = "")
  public String getBudgetDesc() {
    return budgetDesc;
  }

  public void setBudgetDesc(String budgetDesc) {
    this.budgetDesc = budgetDesc;
  }

  public BudgetQueryRequest category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public BudgetQueryRequest current(Integer current) {
    this.current = current;
    return this;
  }

   /**
   * Get current
   * @return current
  **/
  @ApiModelProperty(value = "")
  public Integer getCurrent() {
    return current;
  }

  public void setCurrent(Integer current) {
    this.current = current;
  }

  public BudgetQueryRequest endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public BudgetQueryRequest id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public BudgetQueryRequest notId(Long notId) {
    this.notId = notId;
    return this;
  }

   /**
   * Get notId
   * @return notId
  **/
  @ApiModelProperty(value = "")
  public Long getNotId() {
    return notId;
  }

  public void setNotId(Long notId) {
    this.notId = notId;
  }

  public BudgetQueryRequest pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @ApiModelProperty(value = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public BudgetQueryRequest searchText(String searchText) {
    this.searchText = searchText;
    return this;
  }

   /**
   * Get searchText
   * @return searchText
  **/
  @ApiModelProperty(value = "")
  public String getSearchText() {
    return searchText;
  }

  public void setSearchText(String searchText) {
    this.searchText = searchText;
  }

  public BudgetQueryRequest sortField(String sortField) {
    this.sortField = sortField;
    return this;
  }

   /**
   * Get sortField
   * @return sortField
  **/
  @ApiModelProperty(value = "")
  public String getSortField() {
    return sortField;
  }

  public void setSortField(String sortField) {
    this.sortField = sortField;
  }

  public BudgetQueryRequest sortOrder(String sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * Get sortOrder
   * @return sortOrder
  **/
  @ApiModelProperty(value = "")
  public String getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(String sortOrder) {
    this.sortOrder = sortOrder;
  }

  public BudgetQueryRequest startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public BudgetQueryRequest userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BudgetQueryRequest budgetQueryRequest = (BudgetQueryRequest) o;
    return Objects.equals(this.accountId, budgetQueryRequest.accountId) &&
        Objects.equals(this.amount, budgetQueryRequest.amount) &&
        Objects.equals(this.budgetDesc, budgetQueryRequest.budgetDesc) &&
        Objects.equals(this.category, budgetQueryRequest.category) &&
        Objects.equals(this.current, budgetQueryRequest.current) &&
        Objects.equals(this.endDate, budgetQueryRequest.endDate) &&
        Objects.equals(this.id, budgetQueryRequest.id) &&
        Objects.equals(this.notId, budgetQueryRequest.notId) &&
        Objects.equals(this.pageSize, budgetQueryRequest.pageSize) &&
        Objects.equals(this.searchText, budgetQueryRequest.searchText) &&
        Objects.equals(this.sortField, budgetQueryRequest.sortField) &&
        Objects.equals(this.sortOrder, budgetQueryRequest.sortOrder) &&
        Objects.equals(this.startDate, budgetQueryRequest.startDate) &&
        Objects.equals(this.userId, budgetQueryRequest.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, amount, budgetDesc, category, current, endDate, id, notId, pageSize, searchText, sortField, sortOrder, startDate, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BudgetQueryRequest {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    budgetDesc: ").append(toIndentedString(budgetDesc)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    current: ").append(toIndentedString(current)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    notId: ").append(toIndentedString(notId)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    searchText: ").append(toIndentedString(searchText)).append("\n");
    sb.append("    sortField: ").append(toIndentedString(sortField)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

