/*
 * 接口文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * FinancialRecordAddRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-10T02:09:28.592Z")
public class FinancialRecordAddRequest {
  @SerializedName("accountId")
  private Long accountId = null;

  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("transactionDesc")
  private String transactionDesc = null;

  @SerializedName("transactionTime")
  private String transactionTime = null;

  @SerializedName("transactionType")
  private Integer transactionType = null;

  public FinancialRecordAddRequest accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public FinancialRecordAddRequest amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public FinancialRecordAddRequest category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public FinancialRecordAddRequest transactionDesc(String transactionDesc) {
    this.transactionDesc = transactionDesc;
    return this;
  }

   /**
   * Get transactionDesc
   * @return transactionDesc
  **/
  @ApiModelProperty(value = "")
  public String getTransactionDesc() {
    return transactionDesc;
  }

  public void setTransactionDesc(String transactionDesc) {
    this.transactionDesc = transactionDesc;
  }

  public FinancialRecordAddRequest transactionTime(String transactionTime) {
    this.transactionTime = transactionTime;
    return this;
  }

   /**
   * Get transactionTime
   * @return transactionTime
  **/
  @ApiModelProperty(value = "")
  public String getTransactionTime() {
    return transactionTime;
  }

  public void setTransactionTime(String transactionTime) {
    this.transactionTime = transactionTime;
  }

  public FinancialRecordAddRequest transactionType(Integer transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Get transactionType
   * @return transactionType
  **/
  @ApiModelProperty(value = "")
  public Integer getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(Integer transactionType) {
    this.transactionType = transactionType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinancialRecordAddRequest financialRecordAddRequest = (FinancialRecordAddRequest) o;
    return Objects.equals(this.accountId, financialRecordAddRequest.accountId) &&
        Objects.equals(this.amount, financialRecordAddRequest.amount) &&
        Objects.equals(this.category, financialRecordAddRequest.category) &&
        Objects.equals(this.transactionDesc, financialRecordAddRequest.transactionDesc) &&
        Objects.equals(this.transactionTime, financialRecordAddRequest.transactionTime) &&
        Objects.equals(this.transactionType, financialRecordAddRequest.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, amount, category, transactionDesc, transactionTime, transactionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinancialRecordAddRequest {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    transactionDesc: ").append(toIndentedString(transactionDesc)).append("\n");
    sb.append("    transactionTime: ").append(toIndentedString(transactionTime)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

